"""initial migration

Revision ID: 7b13ed7d1618
Revises: 
Create Date: 2026-01-08 14:56:03.648162

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7b13ed7d1618'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar tabelas primeiro SEM foreign keys para resolver dependência circular
    op.create_table('users',
    sa.Column('cpf_user', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('funcao', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cpf_user')
    )
    
    op.create_table('times',
    sa.Column('id_time', sa.Integer(), nullable=False),
    sa.Column('nome_time', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('responsabilidades', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('cpf_lider', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id_time'),
    sa.UniqueConstraint('cpf_lider'),
    sa.UniqueConstraint('nome_time')
    )
    
    # Adicionar foreign keys DEPOIS que ambas as tabelas existem
    op.create_foreign_key('fk_users_id_time', 'users', 'times', ['id_time'], ['id_time'])
    op.create_foreign_key('fk_times_cpf_lider', 'times', 'users', ['cpf_lider'], ['cpf_user'])
    
    # Remover tabelas antigas se existirem
    op.execute('DROP TABLE IF EXISTS users_team CASCADE')
    op.execute('DROP TABLE IF EXISTS teams CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id_time', sa.INTEGER(), server_default=sa.text("nextval('teams_id_time_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('responsabilidade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_time', name='teams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_teams_nome_time'), 'teams', ['nome_time'], unique=False)
    op.create_table('users_team',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cpf', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('funcao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_time'], ['teams.id_time'], name=op.f('users_team_id_time_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_team_pkey')),
    sa.UniqueConstraint('cpf', name=op.f('uq_cpf_unique'))
    )
    op.create_index(op.f('ix_users_team_cpf'), 'users_team', ['cpf'], unique=True)
    op.create_index(op.f('idx_one_leader_per_team'), 'users_team', ['id_time'], unique=True, postgresql_where="((funcao)::text = 'LIDER'::text)")
    op.drop_table('users')
    op.drop_table('times')
    # ### end Alembic commands ###
